Repository kitabisa/teler, pull requests merged in 2020-10, with the labels that each got.

#34 Enhancement/add unit tests
  pkg/errors/errors.go
  pkg/matchers/config.go
  pkg/matchers/config_test.go
Labels: Priority: Low, Status: Review Needed

#38 Add Telegram alerting
  .gitignore
  CHANGELOG.md
  README.md
  go.mod
  go.sum
  internal/alert/alert.go
  internal/alert/telegram.go
  internal/alert/template/telegram.tmpl
  teler.example.yaml
Labels: Status: Accepted, Status: Review Needed

#42 Add Exporters to Prometheus
  CHANGELOG.md
  README.md
  cmd/teler/main.go
  common/options.go
  go.mod
  go.sum
  internal/runner/options.go
  internal/runner/runner.go
  pkg/metrics/metrics.go
  pkg/teler/teler.go
Labels: Status: Accepted, Status: On Hold, Status: Review Needed
