Repository kitabisa/teler, pull requests merged in 2020-11, with the labels that each got.

#46 Add Caching Resources
  CHANGELOG.md
  README.md
  go.mod
  go.sum
  internal/runner/constants.go
  pkg/cache/cache.go
  pkg/requests/resources.go
  resource/config.go
Labels: Status: Review Needed, Type: Enhancement

#48 Add Docker Hub workflow
  .github/workflows/build-push-dockerhub.yaml
  Dockerfile
  README.md
  pkg/errors/abort.go
Labels: Status: Accepted, Status: Review Needed

#50 Add JSON output format options
  CHANGELOG.md
  README.md
  common/options.go
  go.mod
  go.sum
  internal/runner/constants.go
  internal/runner/options.go
  internal/runner/runner.go
Labels: Status: Review Needed

#53 Merge Docker Hub steps into release action
  .github/workflows/build-push-dockerhub.yaml
  .github/workflows/release.yaml
Labels: Status: Accepted, Status: Review Needed, Type: Maintenance

#58 Fix Slack token validation
  CHANGELOG.md
  pkg/matchers/patterns.go
Labels: Status: Accepted, Status: Review Needed

#69 Release v1.0.0-rc
  CHANGELOG.md
  README.md
  go.mod
  go.sum
  internal/runner/banner.go
  internal/runner/constants.go
  internal/runner/runner.go
  pkg/errors/errors.go
  pkg/metrics/metrics.go
  pkg/requests/resources.go
  pkg/teler/teler.go
  resource/config.go
  teler.example.yaml
Labels: Status: Review Needed, Type: Enhancement
