Repository kitabisa/teler, pull requests merged in 2022-06, with the labels that each got.

#233 Metrics for custom threat rules
  internal/runner/runner.go
  pkg/metrics/metrics.go
  pkg/metrics/prometheus.go
Labels: Type: Enhancement, Status: Revision Needed, Status: Available, Priority: Medium

#235 feat: live event dashboard
  Makefile
  go.mod
  go.sum
  internal/alert/alert.go
  internal/event/event.go
  internal/event/server.go
  internal/event/vars.go
  internal/event/www/index.html
  internal/event/www/script.js
  internal/event/www/signatures.json
  internal/event/www/style.css
  internal/runner/runner.go
  internal/runner/validator.go
  pkg/parsers/config.go
  pkg/parsers/dashboard.go
  pkg/utils/title.go
  teler.example.yaml
Labels: Type: Enhancement, Status: Completed, Priority: Low

#236 WIP: webhooking alert if any
  go.mod
  go.sum
  internal/alert/alert.go
  internal/alert/discord.go
  internal/alert/slack.go
  internal/runner/validator.go
  pkg/errors/constants.go
  pkg/matchers/config.go
  pkg/matchers/patterns.go
  pkg/parsers/notifications.go
  teler.example.yaml
Labels: Type: Enhancement, Status: In Progress, Priority: Medium

#238 feat: add mattermost alert provider
  internal/alert/alert.go
  internal/alert/mattermost.go
  internal/runner/validator.go
  pkg/matchers/config.go
  pkg/matchers/patterns.go
  pkg/parsers/config.go
  teler.example.yaml
Labels: Type: Enhancement, Priority: Medium
